/// <reference types="expo/types" />

// NOTE: This file should not be edited and it's automatically generated by Expo.
// It provides the ambient types for process.env.EXPO_PUBLIC_* and Expo globals.
